name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: darwin
    steps:
      - uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Get dependencies
        run: |
          export PATH=$PATH:~/go/bin/

      - name: build cli
        run: go build -a -o release/highwayhash-cli_$GOOS_$GOARCH
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}

      - name: Upload binary files (linux_amd64)
        uses: actions/upload-artifact@v2
        with:
          name: highwayhash-cli_linux_amd64
          path: release/highwayhash-cli*linux_amd64.*

      - name: Upload binary files (darwin_amd64)
        uses: actions/upload-artifact@v2
        with:
          name: highwayhash-cli_darwin_amd64
          path: release/highwayhash-cli*darwin_amd64.*

      - name: Upload binary files (linux_arm64)
        uses: actions/upload-artifact@v2
        with:
          name: highwayhash-cli_linux_arm64
          path: release/highwayhash-cli*linux_arm64.*

      - name: Upload binary files (darwin_arm64)
        uses: actions/upload-artifact@v2
        with:
          name: highwayhash-cli_darwin_arm64
          path: release/highwayhash-cli*darwin_arm64.*
